export const sampleWardrobe = [
  {
    name: "Ivory Linen Shirt",
    category: "Shirt/Top",
    brand: "Uniqlo",
    color: "#E7D9C8",
    colorName: "Beige",
    size: "M",
    material: "Linen",
    occasion: "office",
    season: "summer",
    estimatedValue: 1990,
  },
  {
    name: "Indigo Straight Jeans",
    category: "Jeans",
    brand: "Levis",
    color: "#1E4F8A",
    colorName: "Indigo",
    size: "32",
    material: "Denim",
    occasion: "casual",
    season: "all-season",
    estimatedValue: 3499,
  },
  {
    name: "Wine Silk Kurta",
    category: "Kurta",
    brand: "Fabindia",
    color: "#7A2438",
    colorName: "Maroon",
    size: "M",
    material: "Silk blend",
    occasion: "ethnic",
    season: "all-season",
    estimatedValue: 4290,
  },
  {
    name: "Gold Festive Lehenga",
    category: "Lehenga",
    brand: "Aza",
    color: "#D69A2D",
    colorName: "Gold",
    size: "M",
    material: "Brocade",
    occasion: "wedding",
    season: "winter",
    estimatedValue: 18900,
  },
  {
    name: "Emerald Cotton Saree",
    category: "Saree",
    brand: "Local Loom",
    color: "#264D46",
    colorName: "Emerald",
    size: "Free size",
    material: "Cotton",
    occasion: "ethnic",
    season: "summer",
    estimatedValue: 5200,
  },
  {
    name: "Black Block Heels",
    category: "Shoes",
    brand: "Mochi",
    color: "#171012",
    colorName: "Black",
    size: "8",
    material: "Faux leather",
    occasion: "party",
    season: "all-season",
    estimatedValue: 2499,
  },
  {
    name: "Tan Leather Juttis",
    category: "Shoes",
    brand: "Needledust",
    color: "#78350F",
    colorName: "Brown",
    size: "8",
    material: "Leather",
    occasion: "wedding",
    season: "all-season",
    estimatedValue: 3200,
  },
  {
    name: "Pearl Clutch",
    category: "Accessories",
    brand: "Accessorize",
    color: "#FFFFFF",
    colorName: "White",
    size: "",
    material: "Beaded",
    occasion: "wedding",
    season: "all-season",
    estimatedValue: 1799,
  },
];
